# Generated by Django 5.1.4 on 2025-01-01 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_room_options_room_paticipants'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='paticipants',
            new_name='participants',
        ),
    ]
